CREATE TABLE IF NOT EXISTS core.dim_country (
    country_key BIGINT GENERATED BY DEFAULT AS IDENTITY (1, 1),
    country_iso3_code CHAR(3) NOT NULL,
    country_id VARCHAR(16),
    country_name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    updated_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (country_key),
    UNIQUE (country_iso3_code)
)
DISTSTYLE AUTO
SORTKEY AUTO;

CREATE TABLE IF NOT EXISTS core.dim_indicator (
    indicator_key BIGINT GENERATED BY DEFAULT AS IDENTITY (1, 1),
    indicator_id VARCHAR(32) NOT NULL,
    indicator_name VARCHAR(256) NOT NULL,
    unit VARCHAR(64),
    decimal_places INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    updated_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (indicator_key),
    UNIQUE (indicator_id)
)
DISTSTYLE AUTO
SORTKEY AUTO;

CREATE TABLE IF NOT EXISTS core.fact_population (
    country_key BIGINT NOT NULL REFERENCES core.dim_country (country_key),
    indicator_key BIGINT NOT NULL REFERENCES core.dim_indicator (indicator_key),
    observation_year INTEGER NOT NULL,
    population_value BIGINT NOT NULL,
    observation_status VARCHAR(64),
    source_file VARCHAR(2048) NOT NULL,
    source_record_index INTEGER NOT NULL,
    load_run_id VARCHAR(128) NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (country_key, indicator_key, observation_year)
)
DISTSTYLE AUTO
SORTKEY AUTO;
